// Vendor the self-hosted DuckDB-WASM bundles into public/duckdb/ so the app runs fully
// offline (the PWA precaches them). We copy ONLY the mvp + eh bundles — never coi —
// because GitHub Pages cannot send COOP/COEP, so there is no SharedArrayBuffer / cross-
// origin isolation and the threaded (coi) bundle is unusable. Mirrors the Pyodide vendor
// step: public/duckdb/ is gitignored and regenerated by `npm run vendor` (CI runs it too).
import { createRequire } from 'node:module';
import { cp, mkdir, rm, stat } from 'node:fs/promises';
import path from 'node:path';

const require = createRequire(import.meta.url);

function resolveDistDir() {
  // Robust across npm hoisting and packages that block the "./package.json" export.
  try {
    return path.join(path.dirname(require.resolve('@duckdb/duckdb-wasm/package.json')), 'dist');
  } catch {
    /* exports may forbid the package.json subpath — fall through */
  }
  try {
    return path.dirname(require.resolve('@duckdb/duckdb-wasm')); // main entry lives in dist/
  } catch {
    /* last resort: the conventional install location, resolved from the repo root */
  }
  return path.resolve('node_modules/@duckdb/duckdb-wasm/dist');
}

// mvp + eh only. If a future DuckDB release renames these, the stat() below throws loudly.
const FILES = [
  'duckdb-mvp.wasm',
  'duckdb-browser-mvp.worker.js',
  'duckdb-eh.wasm',
  'duckdb-browser-eh.worker.js',
];

const distDir = resolveDistDir();
const outDir = path.resolve('public/duckdb');

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

for (const file of FILES) {
  const src = path.join(distDir, file);
  await stat(src); // fail loudly if a rename/hoist means the source isn't where we expect
  await cp(src, path.join(outDir, file));
}

console.log(`Vendored ${FILES.length} DuckDB-WASM bundle files from ${distDir} → public/duckdb/`);
